[workspace]
members = ["crates/common"]
resolver = "2"

[workspace.dependencies]
prost = "0.12"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
